 # optimization
lr: 0.001
optimizer: "Adam"
batch_size: 128
loss: "dice"
# data
num_workers: 0
pin_memory: True
# model
model: Unet
backbone: resnet18
pretrained: imagenet
load_from: False
# data augmentation
train_trans:
  Resize:
    width: 224
    height: 224
val_trans:
  Resize:
    width: 224
    height: 224
# training params
gpus: 1
precision: 16
max_epochs: 20
# debugging options
train_batches: 1.
shuffle_train: True
val_batches: 1.
val_with_train: True
log: True
path: '../input/uw-madison-gi-tract-image-segmentation/train'
file: '../input/preprocessing/data_procesada.csv'  
