 # optimization
lr: 0.002
optimizer: "Adam"
batch_size: 128
loss: "criterion"
scheduler:
  CosineAnnealingLR:
    eta_min: 0.00001
    t_max: 10
    verbose: True
# data
num_workers: 2
pin_memory: True
# model
model: DeepLabV3Plus
backbone: resnet18
pretrained: imagenet
load_from: False
# data augmentation
train_trans:
  Resize:
    width: 224
    height: 224
  RandomRotate90: {}
  HorizontalFlip: {}
  VerticalFlip: {}
  Transpose: {}
  GridDistortion: {}
  GaussianBlur: {}
  Rotate: {}
val_trans:
  Resize:
    width: 224
    height: 224
# training params
gpus: 1
precision: 16
max_epochs: 15
# debugging options
train_batches: 1.
shuffle_train: True
val_batches: 1.
val_with_train: False
log: True
path: '../input/uw-madison-gi-tract-image-segmentation/train'
file: '../input/preprocessing/data_procesada.csv'  
